<!DOCTYPE html>


<?php
require_once('0/php/functions.php');
?>



<html lang="en">
<head>
    <script src="/0/js/themesetup.js" type="text/javascript"></script>
    <?= head(); ?>

    <script src="/0/js/modal.js" type="text/javascript" defer></script>
    <title>Configuration File - Gorp Docs</title>
</head>



<body>

    <header>
        <?= mobileMenu(); ?>

        Configuration File

        <a id="change-theme" class="button theme"></a>
    </header>
    


    <aside>
        <?= sidebar(); ?>
    </aside>



    <div id="background"></div>
    <main class="article">

        <h1>Gorp's Configuration File</h1>

        <p>The configuration file is located at <mono>/minecraft/gorp.conf</mono> and contains all the global options needed to make Gorp run. As new features are added, more options may be added to this file.</p>



        <h2>Options</h2>

        <div class="table-container">
            <table class="minx">
                <tr>
                    <th>Option</th>
                    <th>Description</th>
                    <th>Expected Value</th>
                    <th>Default Value</th>
                </tr>

                <tr>
                    <td>GAMEVER</td>
                    <td>Minecraft game version. Used by the JAR update utility when looking for the latest JAR build. This will not apply to servers using a <a href="/manage-instances/instance-settings/">custom JAR file</a>.</td>
                    <td><a id="open-modal-1" class="button blue nomargin">See list</a></td>
                    <td>1.19.3</td>
                </tr>

                <tr>
                    <td>RAM</td>
                    <td>Amount of RAM to be allocated to each server instance. This can be <a href="/manage-instances/instance-settings/">overridden</a> on a per-instance basis.</td>
                    <td>Integer followed by <mono>G</mono></td>
                    <td>4G</td>
                </tr>

                <tr>
                    <td>BACKUPS</td>
                    <td>Destination for world backups generated by Gorp. <a href="/manage-worlds/backup/">More about backups</a>.</td>
                    <td>Absolute path to destination</td>
                    <td>/minecraft/backups</td>
                </tr>

                <tr>
                    <td>ARCHIVES</td>
                    <td>Destination for world archives generated by Gorp. <a href="/manage-worlds/archive/">More about archives</a>.</td>
                    <td>Absolute path to destination</td>
                    <td>/minecraft/archives</td>
                </tr>
            </table>
        </div>

        

    </main>



    <div id="modal-1" class="hidden">
        <div class="modal-bg">
            <div class="modal-window">
                <a class="close-modal-button">
                    <img src="/0/img/close.svg" />
                </a>
                <div class="title">Valid GAMEVER Values</div>
                <div class="content bulleted">
                    <ul>
                        <li>1.8.8</li>
                        <li>1.9.4</li>
                        <li>1.10.2</li>
                        <li>1.11.2</li>
                        <li>1.12</li>
                        <li>1.12.1</li>
                        <li>1.12.2</li>
                        <li>1.13-pre7</li>
                        <li>1.13</li>
                        <li>1.13.1</li>
                        <li>1.13.2</li>
                        <li>1.14</li>
                        <li>1.14.1</li>
                        <li>1.14.2</li>
                        <li>1.14.3</li>
                        <li>1.14.4</li>
                        <li>1.15</li>
                        <li>1.15.1</li>
                        <li>1.15.2</li>
                        <li>1.16.1</li>
                        <li>1.16.2</li>
                        <li>1.16.3</li>
                        <li>1.16.4</li>
                        <li>1.16.5</li>
                        <li>1.17</li>
                        <li>1.17.1</li>
                        <li>1.18</li>
                        <li>1.18.1</li>
                        <li>1.18.2</li>
                        <li>1.19</li>
                        <li>1.19.1</li>
                        <li>1.19.2</li>
                        <li>1.19.3</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    

</body>

</html>
