<!DOCTYPE html>


<?php
require_once('0/php/functions.php');
?>



<html lang="en">
<head>
    <script src="/0/js/themesetup.js" type="text/javascript"></script>
    <?= head(); ?>
    
    <title>Configuration - Gorp Docs</title>
</head>



<body>

    <header>
        <?= mobileMenu(); ?>

        Configuring Gorp

        <a id="change-theme" class="button theme"></a>
    </header>
    


    <aside>
        <?= sidebar(); ?>
    </aside>



    <div id="background"></div>
    <main class="article">

        <h1>Configuring Gorp</h1>

        <h2>Change Gorp's Config <span class="tag box green subtle inline">NEW</span></h2>
        
        <pre>gorp config</pre>

        <p>Opens your preferred text editor to change Gorp's configuration file. <strong>Do not edit the file manually, it may caused unexpected behaviour.</strong></p>

        <div class="box subtle blue inline">Gorp will ask for sudo privileges</div>



        <h2>Options</h2>

        <div class="table-container">
            <table class="minx">
                <tr>
                    <th>Option</th>
                    <th>Description</th>
                    <th width="150px">Expected Value</th>
                    <th>Default Value</th>
                </tr>

                <tr>
                    <td>GAMEVER</td>
                    <td>Minecraft game version. Used by the JAR update utility when looking for the latest JAR build. This will not apply to servers using a <a href="/manage-servers/server-settings/">custom JAR file</a>. Using <mono>latest</mono> will always use the latest stable build, including major game version updates.</td>
                    <td><a name="m1" class=" open-modal button blue nomargin">See list</a></td>
                    <td><mono>latest</mono></td>
                </tr>

                <tr>
                    <td>RAM</td>
                    <td>Amount of RAM to be allocated to each server instance. This can be <a href="/manage-servers/server-settings/">overridden</a> on a per-instance basis.</td>
                    <td>Integer followed by <mono>G</mono></td>
                    <td><mono>4G</mono></td>
                </tr>

                <tr>
                    <td>MAX_RAM</td>
                    <td>Maximum amount of RAM you want allocated to Gorp servers. Gorp will not allow a server to start if it will break the RAM limit.</td>
                    <td>Integer followed by <mono>G</mono></td>
                    <td><mono>4G</mono></td>
                </tr>

                <tr>
                    <td>HOMEDIR</td>
                    <td>Game files directory, where server instances, jars, and backups are stored by default.</td>
                    <td>Absolute path</td>
                    <td><em>set during installation</em></td>
                </tr>

                <tr>
                    <td>BACKUP_DEST</td>
                    <td>Destination for world backups generated by Gorp. <a href="/manage-servers/backup/">More about backups</a>.</td>
                    <td>Absolute path</td>
                    <td><em>set during installation</em></td>
                </tr>

                <tr>
                    <td>ARCHIVE_DEST</td>
                    <td>Destination for world archives generated by Gorp. <a href="/manage-servers/archive/">More about archives</a>.</td>
                    <td>Absolute path</td>
                    <td><em>set during installation</em></td>
                </tr>

                <tr>
                    <td>UPDATE_FREQUENCY</td>
                    <td>How often <a href="/utilities/jar-update.php">automatic updates</a> are done for the latest server JAR, in the server's local time zone.</td>
                    <td>Cron expression or <mono>disabled</mono></td>
                    <td><mono>0 4 * * 2</mono></td>
                </tr>

                <tr>
                    <td>TEXT_EDITOR</td>
                    <td>Your preferred text editor.</td>
                    <td><mono>vi</mono>, <mono>vim</mono>, <mono>emacs</mono>, or <mono>nano</mono></td>
                    <td><em>set during first use</em></td>
                </tr>
            </table>
        </div>

        

    </main>



    <div id="m1" class="modal hidden">
        <div class="modal-bg">
            <div class="modal-window">
                <a class="close-modal">
                    <img src="/0/img/close.svg" />
                </a>
                <div class="title">Valid GAMEVER Values</div>
                <div class="content bulleted">
                    <ul>
                        <li>latest</li>
                        <li>1.8.8</li>
                        <li>1.9.4</li>
                        <li>1.10.2</li>
                        <li>1.11.2</li>
                        <li>1.12</li>
                        <li>1.12.1</li>
                        <li>1.12.2</li>
                        <li>1.13-pre7</li>
                        <li>1.13</li>
                        <li>1.13.1</li>
                        <li>1.13.2</li>
                        <li>1.14</li>
                        <li>1.14.1</li>
                        <li>1.14.2</li>
                        <li>1.14.3</li>
                        <li>1.14.4</li>
                        <li>1.15</li>
                        <li>1.15.1</li>
                        <li>1.15.2</li>
                        <li>1.16.1</li>
                        <li>1.16.2</li>
                        <li>1.16.3</li>
                        <li>1.16.4</li>
                        <li>1.16.5</li>
                        <li>1.17</li>
                        <li>1.17.1</li>
                        <li>1.18</li>
                        <li>1.18.1</li>
                        <li>1.18.2</li>
                        <li>1.19</li>
                        <li>1.19.1</li>
                        <li>1.19.2</li>
                        <li>1.19.3</li>
                        <li>1.19.4</li>
                        <li>1.20</li>
                        <li>1.20.1</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    

</body>

</html>
