<!DOCTYPE html>


<?php
require_once('0/php/functions.php');
?>



<html lang="en">
<head>
    <script src="/0/js/themesetup.js" type="text/javascript"></script>
    <?= head(); ?>
    
    <title>Configuration File - Gorp Docs</title>
</head>



<body>

    <header>
        <?= mobileMenu(); ?>

        Configuration File

        <a id="change-theme" class="button theme"></a>
    </header>
    


    <aside>
        <?= sidebar(); ?>
    </aside>



    <div id="background"></div>
    <main class="article">

        <h1>Gorp's Configuration File</h1>

        <p>The configuration file is located at <mono>/usr/local/etc/gorp.conf</mono> and contains all the global options needed to make Gorp run. As new features are added, more options may be added to this file.</p>



        <h2>Options</h2>

        <div class="table-container">
            <table class="minx">
                <tr>
                    <th>Option</th>
                    <th>Description</th>
                    <th width="150px">Expected Value</th>
                    <th>Default Value</th>
                </tr>

                <tr>
                    <td>GAMEVER</td>
                    <td>Minecraft game version. Used by the JAR update utility when looking for the latest JAR build. This will not apply to servers using a <a href="/manage-servers/server-settings/">custom JAR file</a>. Using <mono>latest</mono> will always use the latest stable build, including major game version updates.</td>
                    <td><a name="m1" class=" open-modal button blue nomargin">See list</a></td>
                    <td><mono>latest</mono></td>
                </tr>

                <tr>
                    <td>RAM</td>
                    <td>Amount of RAM to be allocated to each server instance. This can be <a href="/manage-servers/server-settings/">overridden</a> on a per-instance basis.</td>
                    <td>Integer followed by <mono>G</mono></td>
                    <td><mono>4G</mono></td>
                </tr>

                <tr>
                    <td>MAX_RAM</td>
                    <td>Maximum amount of RAM you want allocated to Gorp servers. Gorp will not allow a server to start if it will break the RAM limit.</td>
                    <td>Integer followed by <mono>G</mono></td>
                    <td><mono>4G</mono></td>
                </tr>

                <tr>
                    <td>HOMEDIR</td>
                    <td>Gorp's main directory containing the "backups", "jars", and "servers" directories. This key is automatically set during install.</td>
                    <td>Absolute path</td>
                    <td><em>set during installation</em></td>
                </tr>

                <tr>
                    <td>BACKUPS</td>
                    <td>Destination for world backups generated by Gorp. <a href="/manage-servers/backup/">More about backups</a>.</td>
                    <td>Absolute path</td>
                    <td><em>set during installation</em></td>
                </tr>

                <tr>
                    <td>ARCHIVES</td>
                    <td>Destination for world archives generated by Gorp. <a href="/manage-servers/archive/">More about archives</a>.</td>
                    <td>Absolute path</td>
                    <td><em>set during installation</em></td>
                </tr>
            </table>
        </div>

        

    </main>



    <div id="m1" class="modal hidden">
        <div class="modal-bg">
            <div class="modal-window">
                <a class="close-modal">
                    <img src="/0/img/close.svg" />
                </a>
                <div class="title">Valid GAMEVER Values</div>
                <div class="content bulleted">
                    <ul>
                        <li>latest</li>
                        <li>1.8.8</li>
                        <li>1.9.4</li>
                        <li>1.10.2</li>
                        <li>1.11.2</li>
                        <li>1.12</li>
                        <li>1.12.1</li>
                        <li>1.12.2</li>
                        <li>1.13-pre7</li>
                        <li>1.13</li>
                        <li>1.13.1</li>
                        <li>1.13.2</li>
                        <li>1.14</li>
                        <li>1.14.1</li>
                        <li>1.14.2</li>
                        <li>1.14.3</li>
                        <li>1.14.4</li>
                        <li>1.15</li>
                        <li>1.15.1</li>
                        <li>1.15.2</li>
                        <li>1.16.1</li>
                        <li>1.16.2</li>
                        <li>1.16.3</li>
                        <li>1.16.4</li>
                        <li>1.16.5</li>
                        <li>1.17</li>
                        <li>1.17.1</li>
                        <li>1.18</li>
                        <li>1.18.1</li>
                        <li>1.18.2</li>
                        <li>1.19</li>
                        <li>1.19.1</li>
                        <li>1.19.2</li>
                        <li>1.19.3</li>
                        <li>1.19.4</li>
                        <li>1.20</li>
                        <li>1.20.1</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    

</body>

</html>
